hpFallen = 30  -- HP PARA QUANDO O JOGADOR FOR CAIR (NÃO ALTERA QUE SENÃO BUGAS)
deadTime = 180000  -- TEMPO PARA QUANDO O JOGADOR FOR MORRER APÓS CAIR (SE FOR ALTERAR, ALTE TAMBÉM NO settingC.lua)
--     | MILISSEGUNDOS |